package com.example.roadguideapp.goldhunt.profile

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Single-row explorer profile persisted in `goldhunt.db`.
 * [extensionJson] holds optional future payloads (achievements, radar, story, relics).
 */
@Entity(tableName = "explorer_profile")
internal data class ExplorerProfileEntity(
    @PrimaryKey val id: Int = ExplorerProfileSchema.SINGLETON_ID,
    val explorerLevel: Int = ExplorerProfileSchema.DEFAULT_EXPLORER_LEVEL,
    val currentXp: Long = 0L,
    val totalCredits: Int = 0,
    val totalRoadsDiscovered: Int = 0,
    val totalAreasDiscovered: Int = 0,
    val totalTreasuresCollected: Int = 0,
    val totalSecretPlacesFound: Int = 0,
    val totalClustersDiscovered: Int = 0,
    val totalClustersCompleted: Int = 0,
    val totalPanoramaHuntsCompleted: Int = 0,
    val panoramaHuntStatsTotalHunts: Int = 0,
    val panoramaHuntStatsTargetsFound: Int = 0,
    @ColumnInfo(name = "panoramaHuntStatsCreditsEarned")
    val panoramaHuntStatsRewardsEarned: Int = 0,
    val panoramaHuntStatsXpEarned: Long = 0L,
    @ColumnInfo(name = "panoramaHuntStatsHiddenSymbolCompleted")
    val panoramaHuntStatsHiddenSymbolsFound: Int = 0,
    @ColumnInfo(name = "panoramaHuntStatsObjectHuntCompleted")
    val panoramaHuntStatsObjectsFound: Int = 0,
    @ColumnInfo(name = "panoramaHuntStatsPanoramaPuzzleCompleted")
    val panoramaHuntStatsPanoramaPuzzlesSolved: Int = 0,
    @ColumnInfo(name = "panoramaHuntStatsSecretCodeCompleted")
    val panoramaHuntStatsCodesSolved: Int = 0,
    @ColumnInfo(name = "panoramaHuntStatsRelicHuntCompleted")
    val panoramaHuntStatsRelicHuntsCompleted: Int = 0,
    val totalClusterRewardsEarned: Int = 0,
    val clusterStatsRoadsideCachesFound: Int = 0,
    val clusterStatsExplorerNestsFound: Int = 0,
    val clusterStatsTreasureGardensFound: Int = 0,
    val clusterStatsAncientVaultsFound: Int = 0,
    val clusterStatsLegendaryHoardsFound: Int = 0,
    val clusterStatsRoadsideCachesCompleted: Int = 0,
    val clusterStatsExplorerNestsCompleted: Int = 0,
    val clusterStatsTreasureGardensCompleted: Int = 0,
    val clusterStatsAncientVaultsCompleted: Int = 0,
    val clusterStatsLegendaryHoardsCompleted: Int = 0,
    val secretPlaceCatStatsDiscovered: Int = 0,
    val secretPlaceCatStatsCompleted: Int = 0,
    val secretPlaceCatStatsCreditsEarned: Int = 0,
    val secretPlaceCatStatsXpEarned: Long = 0L,
    val secretPlaceCatStatsBestCategoryId: String? = null,
    val secretPlaceCatStatsRarestCategoryId: String? = null,
    val secretPlaceCatStatsNatureSanctuaryFound: Int = 0,
    val secretPlaceCatStatsScenicViewpointFound: Int = 0,
    val secretPlaceCatStatsHistoricLandmarkFound: Int = 0,
    val secretPlaceCatStatsMysteryZoneFound: Int = 0,
    val secretPlaceCatStatsAncientRelicSiteFound: Int = 0,
    val secretPlaceCatStatsExplorerHideoutFound: Int = 0,
    val secretPlaceCatStatsMythicalPlaceFound: Int = 0,
    val secretPlaceCatStatsLegendarySiteFound: Int = 0,
    val secretPlaceCatStatsNatureSanctuaryCompleted: Int = 0,
    val secretPlaceCatStatsScenicViewpointCompleted: Int = 0,
    val secretPlaceCatStatsHistoricLandmarkCompleted: Int = 0,
    val secretPlaceCatStatsMysteryZoneCompleted: Int = 0,
    val secretPlaceCatStatsAncientRelicSiteCompleted: Int = 0,
    val secretPlaceCatStatsExplorerHideoutCompleted: Int = 0,
    val secretPlaceCatStatsMythicalPlaceCompleted: Int = 0,
    val secretPlaceCatStatsLegendarySiteCompleted: Int = 0,
    val totalDistanceExploredM: Double = 0.0,
    val commonTreasuresFound: Int = 0,
    val uncommonTreasuresFound: Int = 0,
    val rareTreasuresFound: Int = 0,
    val epicTreasuresFound: Int = 0,
    val legendaryTreasuresFound: Int = 0,
    val mythicTreasuresFound: Int = 0,
    val radarStatsTotalScans: Int = 0,
    val radarStatsSuccessfulScans: Int = 0,
    val radarStatsTreasuresFound: Int = 0,
    val radarStatsClustersFound: Int = 0,
    val radarStatsSecretPlacesFound: Int = 0,
    val radarStatsStoryDiscoveries: Int = 0,
    val radarStatsLegendaryDiscoveries: Int = 0,
    val seasonalEventStatsEventsJoined: Int = 0,
    val seasonalEventStatsRewardsEarned: Int = 0,
    val seasonalEventStatsBestEventType: String? = null,
    val seasonalEventStatsFavoriteEventType: String? = null,
    val seasonalEventStatsTreasuresCollected: Int = 0,
    val seasonalEventStatsXpEarned: Long = 0L,
    val seasonalEventStatsCreditsEarned: Int = 0,
    val seasonalEventStatsFragmentsEarned: Int = 0,
    val seasonalEventStatsCompletedCycles: Int = 0,
    val achievementStatsCompletedCount: Int = 0,
    val achievementStatsRareCompleted: Int = 0,
    val achievementStatsLegendaryCompleted: Int = 0,
    val achievementStatsCreditsEarned: Int = 0,
    val achievementStatsXpEarned: Long = 0L,
    val legendaryRelicStatsCatalogCount: Int = 0,
    val legendaryRelicStatsCompletedCount: Int = 0,
    val legendaryRelicStatsPiecesCollected: Int = 0,
    val legendaryRelicStatsTotalPieces: Int = 0,
    val legendaryRelicStatsEpicCompleted: Int = 0,
    val legendaryRelicStatsLegendaryCompleted: Int = 0,
    val legendaryRelicStatsCreditsEarned: Int = 0,
    val legendaryRelicStatsXpEarned: Long = 0L,
    val legendaryRelicStatsHiddenCatalogCount: Int = 0,
    val legendaryRelicStatsHiddenRevealed: Int = 0,
    val legendaryRelicStatsHiddenUndiscovered: Int = 0,
    val activeAchievementTitleKey: String? = null,
    val schemaVersion: Int = ExplorerProfileSchema.VERSION,
    val extensionJson: String = ExplorerProfileSchema.EMPTY_EXTENSIONS_JSON,
    val createdAtMs: Long = 0L,
    val updatedAtMs: Long = 0L,
)
