package com.example.roadguideapp.goldhunt.profile

import com.example.roadguideapp.goldhunt.achievements.registry.AchievementRegistry
import com.example.roadguideapp.goldhunt.achievements.statistics.AchievementStatisticsMapper
import com.example.roadguideapp.goldhunt.relics.statistics.LegendaryRelicStatisticsMapper
import com.example.roadguideapp.goldhunt.clusters.statistics.TreasureClusterStatisticsMapper
import com.example.roadguideapp.goldhunt.panorama.statistics.PanoramaHuntStatisticsMapper
import com.example.roadguideapp.goldhunt.events.statistics.SeasonalEventStatisticsMapper
import com.example.roadguideapp.goldhunt.radar.statistics.RadarStatisticsMapper
import com.example.roadguideapp.goldhunt.secretplaces.statistics.SecretPlaceCategoryStatisticsMapper
import com.example.roadguideapp.goldhunt.treasure.stats.TreasureRarityStatistics

internal object ExplorerProfileMapper {
    fun toDomain(entity: ExplorerProfileEntity): ExplorerProfile = ExplorerProfile(
        explorerLevel = entity.explorerLevel,
        currentXp = entity.currentXp,
        totalCredits = entity.totalCredits,
        totalRoadsDiscovered = entity.totalRoadsDiscovered,
        totalAreasDiscovered = entity.totalAreasDiscovered,
        totalTreasuresCollected = entity.totalTreasuresCollected,
        totalSecretPlacesFound = entity.totalSecretPlacesFound,
        totalClustersDiscovered = entity.totalClustersDiscovered,
        totalClustersCompleted = entity.totalClustersCompleted,
        totalPanoramaHuntsCompleted = entity.totalPanoramaHuntsCompleted,
        totalDistanceExploredM = entity.totalDistanceExploredM,
        treasureRarityStats = treasureRarityStatsFromEntity(entity),
        clusterStatistics = TreasureClusterStatisticsMapper.fromEntity(entity),
        secretPlaceCategoryStatistics = SecretPlaceCategoryStatisticsMapper.fromEntity(entity),
        panoramaHuntStatistics = PanoramaHuntStatisticsMapper.fromEntity(entity),
        radarStatistics = RadarStatisticsMapper.fromEntity(entity),
        seasonalEventStatistics = SeasonalEventStatisticsMapper.fromEntity(entity),
        achievementStatistics = AchievementStatisticsMapper.fromEntity(
            entity = entity,
            catalogSize = AchievementRegistry.count(),
        ),
        legendaryRelicStatistics = LegendaryRelicStatisticsMapper.fromEntity(entity),
        hiddenRelicDiscoveryStatistics = LegendaryRelicStatisticsMapper.fromEntity(entity)
            .toHiddenDiscoveryStatistics(),
        activeAchievementTitleKey = entity.activeAchievementTitleKey,
        schemaVersion = entity.schemaVersion,
        extensionJson = entity.extensionJson,
        createdAtMs = entity.createdAtMs,
        updatedAtMs = entity.updatedAtMs,
    )

    fun toEntity(
        profile: ExplorerProfile,
        id: Int = ExplorerProfileSchema.SINGLETON_ID,
    ): ExplorerProfileEntity = ExplorerProfileEntity(
        id = id,
        explorerLevel = profile.explorerLevel,
        currentXp = profile.currentXp,
        totalCredits = profile.totalCredits,
        totalRoadsDiscovered = profile.totalRoadsDiscovered,
        totalAreasDiscovered = profile.totalAreasDiscovered,
        totalTreasuresCollected = profile.totalTreasuresCollected,
        totalSecretPlacesFound = profile.totalSecretPlacesFound,
        totalClustersDiscovered = profile.totalClustersDiscovered,
        totalClustersCompleted = profile.totalClustersCompleted,
        totalPanoramaHuntsCompleted = profile.totalPanoramaHuntsCompleted,
        totalDistanceExploredM = profile.totalDistanceExploredM,
        totalClusterRewardsEarned = profile.clusterStatistics.totalRewardsEarned,
        clusterStatsRoadsideCachesFound = profile.clusterStatistics.roadsideCachesFound,
        clusterStatsExplorerNestsFound = profile.clusterStatistics.explorerNestsFound,
        clusterStatsTreasureGardensFound = profile.clusterStatistics.treasureGardensFound,
        clusterStatsAncientVaultsFound = profile.clusterStatistics.ancientVaultsFound,
        clusterStatsLegendaryHoardsFound = profile.clusterStatistics.legendaryHoardsFound,
        clusterStatsRoadsideCachesCompleted = profile.clusterStatistics.roadsideCachesCompleted,
        clusterStatsExplorerNestsCompleted = profile.clusterStatistics.explorerNestsCompleted,
        clusterStatsTreasureGardensCompleted = profile.clusterStatistics.treasureGardensCompleted,
        clusterStatsAncientVaultsCompleted = profile.clusterStatistics.ancientVaultsCompleted,
        clusterStatsLegendaryHoardsCompleted = profile.clusterStatistics.legendaryHoardsCompleted,
        secretPlaceCatStatsDiscovered = profile.secretPlaceCategoryStatistics.discoveredCount,
        secretPlaceCatStatsCompleted = profile.secretPlaceCategoryStatistics.completedCount,
        secretPlaceCatStatsCreditsEarned = profile.secretPlaceCategoryStatistics.creditsEarned,
        secretPlaceCatStatsXpEarned = profile.secretPlaceCategoryStatistics.xpEarned,
        secretPlaceCatStatsBestCategoryId = profile.secretPlaceCategoryStatistics.bestCategory?.id,
        secretPlaceCatStatsRarestCategoryId = profile.secretPlaceCategoryStatistics.rarestCategory?.id,
        secretPlaceCatStatsNatureSanctuaryFound = profile.secretPlaceCategoryStatistics.natureSanctuariesFound,
        secretPlaceCatStatsScenicViewpointFound = profile.secretPlaceCategoryStatistics.scenicViewpointsFound,
        secretPlaceCatStatsHistoricLandmarkFound = profile.secretPlaceCategoryStatistics.historicLandmarksFound,
        secretPlaceCatStatsMysteryZoneFound = profile.secretPlaceCategoryStatistics.mysteryZonesFound,
        secretPlaceCatStatsAncientRelicSiteFound = profile.secretPlaceCategoryStatistics.ancientRelicSitesFound,
        secretPlaceCatStatsExplorerHideoutFound = profile.secretPlaceCategoryStatistics.explorerHideoutsFound,
        secretPlaceCatStatsMythicalPlaceFound = profile.secretPlaceCategoryStatistics.mythicalPlacesFound,
        secretPlaceCatStatsLegendarySiteFound = profile.secretPlaceCategoryStatistics.legendarySitesFound,
        secretPlaceCatStatsNatureSanctuaryCompleted = profile.secretPlaceCategoryStatistics.natureSanctuariesCompleted,
        secretPlaceCatStatsScenicViewpointCompleted = profile.secretPlaceCategoryStatistics.scenicViewpointsCompleted,
        secretPlaceCatStatsHistoricLandmarkCompleted = profile.secretPlaceCategoryStatistics.historicLandmarksCompleted,
        secretPlaceCatStatsMysteryZoneCompleted = profile.secretPlaceCategoryStatistics.mysteryZonesCompleted,
        secretPlaceCatStatsAncientRelicSiteCompleted = profile.secretPlaceCategoryStatistics.ancientRelicSitesCompleted,
        secretPlaceCatStatsExplorerHideoutCompleted = profile.secretPlaceCategoryStatistics.explorerHideoutsCompleted,
        secretPlaceCatStatsMythicalPlaceCompleted = profile.secretPlaceCategoryStatistics.mythicalPlacesCompleted,
        secretPlaceCatStatsLegendarySiteCompleted = profile.secretPlaceCategoryStatistics.legendarySitesCompleted,
        panoramaHuntStatsTotalHunts = profile.panoramaHuntStatistics.totalHunts,
        panoramaHuntStatsTargetsFound = profile.panoramaHuntStatistics.targetsFound,
        panoramaHuntStatsRewardsEarned = profile.panoramaHuntStatistics.rewardsEarned,
        panoramaHuntStatsXpEarned = profile.panoramaHuntStatistics.xpEarned,
        panoramaHuntStatsHiddenSymbolsFound = profile.panoramaHuntStatistics.hiddenSymbolsFound,
        panoramaHuntStatsObjectsFound = profile.panoramaHuntStatistics.objectsFound,
        panoramaHuntStatsPanoramaPuzzlesSolved = profile.panoramaHuntStatistics.panoramaPuzzlesSolved,
        panoramaHuntStatsCodesSolved = profile.panoramaHuntStatistics.codesSolved,
        panoramaHuntStatsRelicHuntsCompleted = profile.panoramaHuntStatistics.relicHuntsCompleted,
        commonTreasuresFound = profile.treasureRarityStats.commonFound,
        uncommonTreasuresFound = profile.treasureRarityStats.uncommonFound,
        rareTreasuresFound = profile.treasureRarityStats.rareFound,
        epicTreasuresFound = profile.treasureRarityStats.epicFound,
        legendaryTreasuresFound = profile.treasureRarityStats.legendaryFound,
        mythicTreasuresFound = profile.treasureRarityStats.mythicFound,
        radarStatsTotalScans = profile.radarStatistics.totalScans,
        radarStatsSuccessfulScans = profile.radarStatistics.successfulScans,
        radarStatsTreasuresFound = profile.radarStatistics.treasuresFound,
        radarStatsClustersFound = profile.radarStatistics.clustersFound,
        radarStatsSecretPlacesFound = profile.radarStatistics.secretPlacesFound,
        radarStatsStoryDiscoveries = profile.radarStatistics.storyDiscoveries,
        radarStatsLegendaryDiscoveries = profile.radarStatistics.legendaryDiscoveries,
        seasonalEventStatsEventsJoined = profile.seasonalEventStatistics.eventsJoined,
        seasonalEventStatsRewardsEarned = profile.seasonalEventStatistics.rewardsEarned,
        seasonalEventStatsBestEventType = profile.seasonalEventStatistics.bestEventType?.id,
        seasonalEventStatsFavoriteEventType = profile.seasonalEventStatistics.favoriteEventType?.id,
        seasonalEventStatsTreasuresCollected = profile.seasonalEventStatistics.treasuresCollected,
        seasonalEventStatsXpEarned = profile.seasonalEventStatistics.xpEarned,
        seasonalEventStatsCreditsEarned = profile.seasonalEventStatistics.creditsEarned,
        seasonalEventStatsFragmentsEarned = profile.seasonalEventStatistics.fragmentsEarned,
        seasonalEventStatsCompletedCycles = profile.seasonalEventStatistics.eventsCompleted,
        achievementStatsCompletedCount = profile.achievementStatistics.completedCount,
        achievementStatsRareCompleted = profile.achievementStatistics.rareCompletedCount,
        achievementStatsLegendaryCompleted = profile.achievementStatistics.legendaryCompletedCount,
        achievementStatsCreditsEarned = profile.achievementStatistics.creditsEarned,
        achievementStatsXpEarned = profile.achievementStatistics.xpEarned,
        legendaryRelicStatsCatalogCount = profile.legendaryRelicStatistics.catalogCount,
        legendaryRelicStatsCompletedCount = profile.legendaryRelicStatistics.completedCount,
        legendaryRelicStatsPiecesCollected = profile.legendaryRelicStatistics.piecesCollected,
        legendaryRelicStatsTotalPieces = profile.legendaryRelicStatistics.totalPieces,
        legendaryRelicStatsEpicCompleted = profile.legendaryRelicStatistics.epicCompletedCount,
        legendaryRelicStatsLegendaryCompleted = profile.legendaryRelicStatistics.legendaryCompletedCount,
        legendaryRelicStatsCreditsEarned = profile.legendaryRelicStatistics.creditsEarned,
        legendaryRelicStatsXpEarned = profile.legendaryRelicStatistics.xpEarned,
        legendaryRelicStatsHiddenCatalogCount = profile.legendaryRelicStatistics.hiddenRelicsCatalogCount,
        legendaryRelicStatsHiddenRevealed = profile.legendaryRelicStatistics.hiddenRelicsDiscovered,
        legendaryRelicStatsHiddenUndiscovered = profile.legendaryRelicStatistics.hiddenRelicsUndiscovered,
        activeAchievementTitleKey = profile.activeAchievementTitleKey,
        schemaVersion = profile.schemaVersion,
        extensionJson = profile.extensionJson,
        createdAtMs = profile.createdAtMs,
        updatedAtMs = profile.updatedAtMs,
    )

    fun treasureRarityStatsFromEntity(entity: ExplorerProfileEntity): TreasureRarityStatistics =
        TreasureRarityStatistics(
            commonFound = entity.commonTreasuresFound,
            uncommonFound = entity.uncommonTreasuresFound,
            rareFound = entity.rareTreasuresFound,
            epicFound = entity.epicTreasuresFound,
            legendaryFound = entity.legendaryTreasuresFound,
            mythicFound = entity.mythicTreasuresFound,
        )
}
